<?php

/**
 * @file
 * Provide a custom markup page.
 */

/**
 * Implements hook_menu().
 */
function easyopac_page_custom_menu() {
  $menu = [];

  $menu['easyopac/page/custom'] = [
    'page callback' => 'easyopac_page_custom_ballback',
    'page arguments' => array(),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  ];

  return $menu;
}

/**
 * Custom page callback.
 */
function easyopac_page_custom_ballback() {
  return theme('eo_page_custom');
}

/**
 * Implements hook_theme().
 */
function easyopac_page_custom_theme($existing, $type, $theme, $path) {
  $hooks = [];

  $hooks['eo_page_custom'] = [
    'variables' => [],
    'template' => 'templates/eo_page_custom',
  ];

  return $hooks;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function easyopac_page_custom_preprocess_eo_page_custom(&$variables) {
  drupal_add_css(drupal_get_path('module', 'easyopac_page_custom') . '/css/eo_page_custom.styles.css');
  drupal_add_js(drupal_get_path('module', 'easyopac_page_custom') . '/js/eo_page_custom.scripts.js', ['type' => 'file']);
}
